### ISSUE TITLE
请问下下onnxruntime_providers_shared.so 和 onnxruntime_providers_cuda.onnx 和onnxruntime.so 关系，ldd也没看到他们的链接关系，我看到你的github上只是链接了onnxruntime.so

### ISSUE THREAD

**Issue by yank666** [wyt95/Yolov3_onnxruntime_cpp#1]
请问下下onnxruntime_providers_shared.so 和 onnxruntime_providers_cuda.onnx 和onnxruntime.so 关系，ldd也没看到他们的链接关系，我看到你的github上只是链接了onnxruntime.so， 我刚刚接触，不太了解

**Comment by wyt95** [comment]
使用onnxruntime需要引入provider的头文件信息，例如<cpu_provider_factory.h>或者<cuda_provider_factory.h>，这些引入推理的接口都是在这些库里面的
