### ISSUE TITLE
不是你的程序的问题,请教一下

### ISSUE THREAD

**Issue by dongwangGithub** [wyt95/Yolov3_onnxruntime_cpp#2]
CMakeFiles/yoloOnnx.dir/yoloOnnx.cpp.o：在函数‘__static_initialization_and_destruction_0(int, int)’中：
yoloOnnx.cpp:(.text+0x48)：对‘OrtGetApiBase’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/yoloOnnx.dir/build.make:96: recipe for target 'yoloOnnx' failed
make[2]: *** [yoloOnnx] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/yoloOnnx.dir/all' failed
make[1]: *** [CMakeFiles/yoloOnnx.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

编译过程中出现的问题,主要是第一二两句,请问这样的问题该怎么处理,我不仅试了你编译的结果,还尝试了官方提供的库

**Comment by wyt95** [comment]
你能详细提供你的代码吗？这个提示你未定义，没办法直接定位您的问题，你可以邮箱提供你的VX或者QQ

**Comment by dongwangGithub** [comment]
我的微信号：17602153528
问题我定位到了，我们可以加个微信，后面可以请教你


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wyt95/Yolov3_onnxruntime_cpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wyt95/Yolov3_onnxruntime_cpp] 不是你的程序的问题,请教一下 (#2)





 
你能详细提供你的代码吗？这个提示你未定义，没办法直接定位您的问题，你可以邮箱提供你的VX或者QQ
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dongwangGithub** [comment]
> 你能详细提供你的代码吗？这个提示你未定义，没办法直接定位您的问题，你可以邮箱提供你的VX或者QQ
我通过你的163邮件回复你了，你可以查看一下邮箱
